[build]
builder = "dockerfile"

[deploy]
startCommand = "node_modules/.bin/prisma migrate deploy && node_modules/.bin/next start"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"
